tabs:
  - name: Application
    url: read-only.html
  - name: Messages
    url: messages.html
  - name: Documents
    subfolderitems:
      - page: Firm Documents
        url: firm-documents.html
      - page: Analyst Documents
        url: analyst-documents.html
  - name: SBA Notes
    url: notes.html
  - name: Activity Log
    url: activity-log.html
