- main_heading: Mike’s Garage
  link_main_heading: true
  secondary_heading: 8(a) Initial Application
  additional_info:
    - key: Owner
      value: Mike Jones (703-555-1234)
    - key: Program year
      value: 3
    - key: District office
      value: Seattle
      editable: true
